
# Executable names:
EXE = testavl

# Add all object files needed for compiling:
EXE_OBJ = test.o
OBJS = test.o  coloredout.o


CLEAN_RM =  tests/*.d tests/*.o

# Use the cs225 makefile template:
include cs225/make/cs225.mk
